version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: journal_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: journal
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 